# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-02 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to=b'')),
                ('caption', models.CharField(max_length=100)),
                ('backtext', models.TextField(max_length=500)),
            ],
        ),
    ]
