# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-02 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeimage',
            name='href',
            field=models.CharField(default='#', max_length=500),
            preserve_default=False,
        ),
    ]
