# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180927_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalimage',
            name='caption',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='potraitimage',
            name='caption',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stillimage',
            name='caption',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='weddingimage',
            name='caption',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
